name: Pull Request
on:
  pull_request:
  push:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }} - ${{ github.event.pull_request.id }}
  cancel-in-progress: true

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout Repository
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/setup-pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: latest
          run_install: false

      # https://github.com/marketplace/actions/setup-node-js-environment
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: lts/*
          check-latest: true

      - name: Install dependencies
        run: pnpm recursive install ${{ github.actor != 'dependabot[bot]' && '--frozen-lockfile' || '--no-frozen-lockfile' }}

      - run: echo "${{ toJSON(env) }}"

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Unit-Tests
        run: pnpm test

